-- Supabase Schema for Caniluma Booking System

-- 1. Create slots table
CREATE TABLE IF NOT EXISTS public.slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "startTime" TIMESTAMP WITH TIME ZONE NOT NULL,
    "endTime" TIMESTAMP WITH TIME ZONE NOT NULL,
    "isBooked" SMALLINT DEFAULT 0 NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('einzel', 'gruppe')),
    "maxCapacity" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create bookings table
CREATE TABLE IF NOT EXISTS public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "slotId" BIGINT NOT NULL REFERENCES public.slots(id) ON DELETE CASCADE,
    "parentName" TEXT NOT NULL,
    "childName" TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    notes TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create settings table (for admin password)
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Set default admin password (caniluma2025)
-- Note: In a real production app, you should hash this password.
-- For this simple setup, we use plain text as requested in the initial requirements.
INSERT INTO public.settings (key, value)
VALUES ('admin_password', 'caniluma2025')
ON CONFLICT (key) DO NOTHING;

-- 5. Enable Row Level Security (RLS)
ALTER TABLE public.slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- 6. Create RLS Policies

-- Slots: Anyone can read slots (for the booking page)
CREATE POLICY "Enable read access for all users on slots" 
ON public.slots FOR SELECT USING (true);

-- Slots: Only service role can insert/update/delete (handled by backend)
CREATE POLICY "Enable all access for service role on slots" 
ON public.slots USING (true) WITH CHECK (true);

-- Bookings: Only service role can read/insert/update/delete (handled by backend)
CREATE POLICY "Enable all access for service role on bookings" 
ON public.bookings USING (true) WITH CHECK (true);

-- Settings: Only service role can read/update (handled by backend)
CREATE POLICY "Enable all access for service role on settings" 
ON public.settings USING (true) WITH CHECK (true);

-- 7. Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_slots_starttime ON public.slots("startTime");
CREATE INDEX IF NOT EXISTS idx_bookings_slotid ON public.bookings("slotId");
CREATE INDEX IF NOT EXISTS idx_bookings_email ON public.bookings(email);

-- Note on Booking Numbers:
-- The booking number (e.g., CNL-10001) is derived dynamically in the application
-- by adding 10000 to the booking's auto-incrementing 'id'.
-- Therefore, no explicit 'bookingNumber' column is required in the database.
