-- Supabase Schema for Caniluma Booking System

-- 1. Create clients table (NEW)
CREATE TABLE IF NOT EXISTS public.clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    "parentName" TEXT NOT NULL,
    "childName" TEXT NOT NULL,
    phone TEXT NOT NULL,
    "clientNumber" TEXT UNIQUE NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create slots table
CREATE TABLE IF NOT EXISTS public.slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "startTime" TIMESTAMP WITH TIME ZONE NOT NULL,
    "endTime" TIMESTAMP WITH TIME ZONE NOT NULL,
    "isBooked" SMALLINT DEFAULT 0 NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('einzel', 'gruppe')),
    "maxCapacity" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create bookings table
CREATE TABLE IF NOT EXISTS public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "slotId" BIGINT NOT NULL REFERENCES public.slots(id) ON DELETE CASCADE,
    "clientId" BIGINT REFERENCES public.clients(id) ON DELETE CASCADE,
    "parentName" TEXT NOT NULL,
    "childName" TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    notes TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create settings table (for admin password)
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Set default admin password (caniluma2025)
INSERT INTO public.settings (key, value)
VALUES ('admin_password', 'caniluma2025')
ON CONFLICT (key) DO NOTHING;

-- 6. Enable Row Level Security (RLS)
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- 7. Create RLS Policies

-- Clients: Only service role can read/insert/update/delete (handled by backend)
CREATE POLICY "Enable all access for service role on clients" 
ON public.clients USING (true) WITH CHECK (true);

-- Slots: Anyone can read slots (for the booking page)
CREATE POLICY "Enable read access for all users on slots" 
ON public.slots FOR SELECT USING (true);

-- Slots: Only service role can insert/update/delete (handled by backend)
CREATE POLICY "Enable all access for service role on slots" 
ON public.slots USING (true) WITH CHECK (true);

-- Bookings: Only service role can read/insert/update/delete (handled by backend)
CREATE POLICY "Enable all access for service role on bookings" 
ON public.bookings USING (true) WITH CHECK (true);

-- Settings: Only service role can read/update (handled by backend)
CREATE POLICY "Enable all access for service role on settings" 
ON public.settings USING (true) WITH CHECK (true);

-- 8. Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_clients_email ON public.clients(email);
CREATE INDEX IF NOT EXISTS idx_clients_clientnumber ON public.clients("clientNumber");
CREATE INDEX IF NOT EXISTS idx_slots_starttime ON public.slots("startTime");
CREATE INDEX IF NOT EXISTS idx_bookings_slotid ON public.bookings("slotId");
CREATE INDEX IF NOT EXISTS idx_bookings_clientid ON public.bookings("clientId");
CREATE INDEX IF NOT EXISTS idx_bookings_email ON public.bookings(email);

-- Note on Client Numbers:
-- The client number (e.g., CNL-10001) is derived dynamically in the application
-- by adding 10000 to the client's auto-incrementing 'id'.
